### ISSUE TITLE
Problem about CNN-Deblur

### ISSUE THREAD

**Issue by BaiYu0120** [sandeepraju/ihradis-cnn-deblur#1]
Hi,
I have run the online deblur process of this paper, but the output is incorrect.
Which the input data type is suitable, 3 channels of RGB?
Or are there anything I should attach importance to it?

Thanks.
Yu

**Comment by sandeepraju** [comment]
you just need to run it as shown in the below command:

```bash
echo "/path/to/input/image.png" | python processWholeImage.py --model_def ../BMVC_nets/S14_19_200.deploy --pretrained_model ../BMVC_nets/S14_19_FQ_178000.model --out_scale 1 --extract_layer CONVX_15 --output_path /path/to/output/folder/ --border 25 --tile_resolution 150
```

here, the input image (image.png) is RGB.
